environment:
  - API_HOST_NAME=api.notifications-api.dev.convox
  - ADMIN_BASE_URL=web.notifications-admin.dev.convox
  - NOTIFY_ENVIRONMENT=development
resources:
  db:
    type: postgres
    options:
      version: 9
  redis:
    type: redis
services:
  api:
    image: bitzesty/notifications-api:latest
    command: 'flask run --host=0.0.0.0 -p 6011'
    domain: ${DOMAIN}
    port: 6011
    resources:
      - db:SQLALCHEMY_DATABASE_URI
      - redis
