environment:
  - API_HOST_NAME=api.notifications-api.dev.convox
  - ADMIN_BASE_URL=web.notifications-admin.dev.convox
  - NOTIFY_ENVIRONMENT=development
  - PYTHONUNBUFFERED=TRUE
resources:
  db:
    type: postgres
    options:
      version: 9
  redis:
    type: redis
services:
  api:
    build:
      path: .
      manifest: docker/Dockerfile.convox
    command: 'gunicorn -c gunicorn_config.py application'
    domain: ${DOMAIN}
    port: 6011
    resources:
      - db:SQLALCHEMY_DATABASE_URI
      - redis
