environment:
  - API_HOST_NAME=api.notifications-api.dev.convox
  - ADMIN_BASE_URL=web.notifications-admin.dev.convox
  - NOTIFY_ENVIRONMENT=development
services:
  api:
    build:
      path: .
      manifest: docker/Dockerfile.convox
    command: 'gunicorn -c gunicorn_config.py application'
    port: 8080