version: '3'

services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: 'db'
      POSTGRES_PASSWORD: 'password'
    ports:
      - 5432:5432

  redis:
    image: redis:3.2.11
    ports:
      - 6379:6379
