version: '3'

services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: 'db'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DBS: 'notification_api, notification_test'
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/docker/postgres/initdb.d:/docker-entrypoint-initdb.d

  redis:
    image: redis:3.2.11
    ports:
      - 6379:6379
