"""

Revision ID: 0361_add_webauthn_auth_type
Revises: 35986aeec764
Create Date: 2021-09-19 12:03:36.197844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0361_add_webauthn_auth_type'
down_revision = '35986aeec764'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("INSERT INTO auth_type VALUES ('webauthn_auth')")

    op.drop_constraint('ck_users_mobile_or_email_auth', 'users', type_=None, schema=None)
    op.execute("""
        ALTER TABLE users ADD CONSTRAINT "ck_user_has_mobile_or_other_auth"
        CHECK (auth_type in ('email_auth', 'webauthn_auth') or mobile_number is not null)
        NOT VALID
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE users SET auth_type = 'sms_auth' WHERE auth_type = 'webauthn_auth'")
    op.execute("UPDATE invited_users SET auth_type = 'sms_auth' WHERE auth_type = 'webauthn_auth'")

    op.drop_constraint('ck_user_has_mobile_or_other_auth', 'users', type_=None, schema=None)
    op.execute("""
        ALTER TABLE users ADD CONSTRAINT "ck_users_mobile_or_email_auth"
        CHECK (auth_type = 'email_auth' or mobile_number is not null)
        NOT VALID
    """)

    op.execute("DELETE FROM auth_type WHERE name = 'webauthn_auth'")
    # ### end Alembic commands ###
