"""

Revision ID: 0362_validate_constraint
Revises: 0361_add_webauthn_auth_type
Create Date: 2021-09-19 12:08:39.854111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0362_validate_constraint'
down_revision = '0361_add_webauthn_auth_type'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE users VALIDATE CONSTRAINT "ck_user_has_mobile_or_other_auth"')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
